shape: sequence_diagram

Community {shape: diamond}
Member {shape: circle}
Election

Community { Generate key pair }
Member { Generate key pair }

Registering users: {
  Community <- Member: Send public key
  Community -> Member: Sign public key
}

Community -> Election: Create

Vote: {
  Member -> Election: Generate and sign ballot
}

Late registration and lost account: {
  Community <- Member: Send new public key
  Community -> Member: Sign new public key
  Community -> Election: Amend voter list
  Member -> Election: Generate and sign ballot
}

Decryption {
  Community -> Election: Tally
  Community <- Election: Publis result
}