// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belenios from "../helpers/Belenios.bs.js";

function make(ballot, election, selection) {
  var trustees = election.trustees;
  var params = JSON.parse(election.params);
  var ciphertext = Belenios.Election.vote(params)("", [selection], trustees);
  return {
          electionTx: ballot.electionTx,
          previousTx: ballot.previousTx,
          owners: ballot.owners,
          ciphertext: ciphertext
        };
}

export {
  make ,
}
/* Belenios Not a pure module */
