// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belenios from "../helpers/Belenios.bs.js";

function make(name, description, choices, ownerPublicKey, trustee) {
  var trustees = trustee.trustees;
  var params = Belenios.Election._create(name, description, choices, trustees);
  return {
          params: params,
          trustees: trustees,
          ownerPublicKey: ownerPublicKey
        };
}

function answers(election) {
  return Belenios.Election.answers(JSON.parse(election.params));
}

function name(election) {
  return JSON.parse(election.params).name;
}

function description(election) {
  return JSON.parse(election.params).description;
}

var choices = answers;

export {
  make ,
  answers ,
  choices ,
  name ,
  description ,
}
/* Belenios Not a pure module */
