// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Identity from "./Identity.bs.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as SjclWithAll from "sjcl-with-all";
import * as AsyncStorage from "@react-native-async-storage/async-storage";

function hash(str) {
  return SjclWithAll.codec.hex.fromBits(SjclWithAll.hash.sha256.hash(str));
}

function make(election, owner) {
  var content = JSON.stringify(election);
  var contentHash = SjclWithAll.codec.hex.fromBits(SjclWithAll.hash.sha256.hash(content));
  return {
          type_: "election",
          content: content,
          contentHash: contentHash,
          publicKey: owner.hexPublicKey,
          signature: Identity.signHex(owner, contentHash)
        };
}

function unwrap(tx) {
  return JSON.parse(tx.content);
}

var SignedElection = {
  make: make,
  unwrap: unwrap
};

function make$1(ballot, owner) {
  var content = JSON.stringify(ballot);
  var contentHash = SjclWithAll.codec.hex.fromBits(SjclWithAll.hash.sha256.hash(content));
  return {
          type_: "ballot",
          content: content,
          contentHash: contentHash,
          publicKey: owner.hexPublicKey,
          signature: Identity.signHex(owner, contentHash)
        };
}

function unwrap$1(tx) {
  return JSON.parse(tx.content);
}

var SignedBallot = {
  make: make$1,
  unwrap: unwrap$1
};

var storageKey = "transactions";

function fetch_all(param) {
  return AsyncStorage.default.getItem(storageKey).then(function (prim) {
                  if (prim === null) {
                    return ;
                  } else {
                    return Caml_option.some(prim);
                  }
                }).then(function (__x) {
                return Belt_Option.map(__x, (function (prim) {
                              return JSON.parse(prim);
                            }));
              }).then(function (__x) {
              return Belt_Option.getWithDefault(__x, []);
            });
}

function store_all(txs) {
  AsyncStorage.default.setItem(storageKey, JSON.stringify(txs));
}

function clear(param) {
  AsyncStorage.default.removeItem(storageKey);
}

export {
  hash ,
  SignedElection ,
  SignedBallot ,
  storageKey ,
  fetch_all ,
  store_all ,
  clear ,
}
/* Identity Not a pure module */
