// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Sjcl from "./Sjcl.bs.js";

function make(param) {
  var match = Sjcl.Ecdsa.$$new(undefined);
  return {
          publicKey: match[0],
          secretKey: match[1]
        };
}

export {
  make ,
}
/* Sjcl Not a pure module */
