// Generated by ReScript, PLEASE EDIT WITH CARE


function make(value, key, color) {
  var svg = {
    fill: color
  };
  return {
          value: value,
          key: key,
          svg: svg
        };
}

var Datum = {
  make: make
};

export {
  Datum ,
}
/* No side effect */
