// Generated by ReScript, PLEASE EDIT WITH CARE

import * as SjclWithAll from "sjcl-with-all";

var BitArray = {};

var Bn = {};

var Hex = {};

var Utf8String = {};

var Sha256 = {};

var Misc = {};

var Aes = {};

var Cipher = {
  Aes: Aes
};

var CCM = {};

var Mode = {
  CCM: CCM
};

var Random = {};

var Curve = {};

var Point = {};

var Ecc = {
  Curve: Curve,
  Point: Point
};

function toHex(t) {
  return t.serialize().point;
}

function fromHex(str) {
  return new (SjclWithAll.ecc.ecdsa.publicKey)(SjclWithAll.ecc.curves.c256, SjclWithAll.codec.hex.toBits(str));
}

var PublicKey = {
  toHex: toHex,
  fromHex: fromHex
};

function toHex$1(t) {
  return t.serialize().exponent;
}

function fromHex$1(str) {
  return new (SjclWithAll.ecc.ecdsa.secretKey)(SjclWithAll.ecc.curves.c256, SjclWithAll.bn.fromBits(SjclWithAll.codec.hex.toBits(str)));
}

function toPub(t) {
  var sec = t.serialize().exponent;
  var curve = SjclWithAll.ecc.curves.c256;
  console.log([
        sec,
        curve
      ]);
  var pub = (curve.G.mult(sec));
  console.log(pub);
  return new (SjclWithAll.ecc.ecdsa.publicKey)(curve, pub);
}

var SecretKey = {
  toHex: toHex$1,
  fromHex: fromHex$1,
  toPub: toPub
};

function generateKeys(param) {
  return SjclWithAll.ecc.ecdsa.generateKeys(undefined, undefined, undefined);
}

function $$new(param) {
  var keys = SjclWithAll.ecc.ecdsa.generateKeys(undefined, undefined, undefined);
  return [
          keys.pub,
          keys.sec
        ];
}

var Ecdsa = {
  PublicKey: PublicKey,
  SecretKey: SecretKey,
  generateKeys: generateKeys,
  $$new: $$new
};

export {
  BitArray ,
  Bn ,
  Hex ,
  Utf8String ,
  Sha256 ,
  Misc ,
  Cipher ,
  Mode ,
  Random ,
  Ecc ,
  Ecdsa ,
}
/* sjcl-with-all Not a pure module */
