// Generated by ReScript, PLEASE EDIT WITH CARE


function to_json(r) {
  return {
          email: r.email,
          publicKey: r.publicKey
        };
}

export {
  to_json ,
}
/* No side effect */
