// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Config from "../Config.bs.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as ReactNativePaper from "react-native-paper";

function Admin_Users(Props) {
  var match = React.useState(function () {
        return [];
      });
  var setUsers = match[1];
  React.useEffect((function () {
          fetch("" + Config.api_url + "/users").then(function (prim) {
                  return prim.json();
                }).then(function (o) {
                Curry._1(setUsers, (function (param) {
                        return o;
                      }));
              });
        }), []);
  return React.createElement(ReactNativePaper.List.Section, {
              title: "Utilisateurs",
              children: Belt_Array.map(match[0], (function (user) {
                      return React.createElement(ReactNativePaper.List.Item, {
                                  onPress: (function (param) {
                                      
                                    }),
                                  title: user.email,
                                  left: (function (param) {
                                      return React.createElement(ReactNativePaper.List.Icon, {
                                                  icon: "account"
                                                });
                                    }),
                                  right: (function (param) {
                                      return React.createElement(ReactNativePaper.List.Icon, {
                                                  icon: "pencil"
                                                });
                                    })
                                });
                    }))
            });
}

var make = Admin_Users;

export {
  make ,
}
/* react Not a pure module */
