// Generated by ReScript, PLEASE EDIT WITH CARE

import * as X from "../X.bs.js";
import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Context from "../state/Context.bs.js";
import * as ReactNativePaper from "react-native-paper";

function User_Register_Confirm(Props) {
  var match = React.useState(function () {
        return "";
      });
  var setToken = match[1];
  Context.use(undefined);
  return React.createElement(React.Fragment, undefined, React.createElement(ReactNativePaper.Title, {
                  style: X.styles.center,
                  children: "Check your emails and enter your token"
                }), React.createElement(ReactNativePaper.TextInput, {
                  mode: "flat",
                  label: "Token",
                  value: match[0],
                  onChangeText: (function (text) {
                      Curry._1(setToken, (function (param) {
                              return text;
                            }));
                    }),
                  testID: "token-input"
                }), React.createElement(ReactNativePaper.Button, {
                  mode: "contained",
                  onPress: (function (param) {
                      
                    }),
                  children: "Se connecter"
                }));
}

var make = User_Register_Confirm;

export {
  make ,
}
/* X Not a pure module */
