// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as VoterList from "../components/VoterList.bs.js";
import * as CandidateList from "../components/CandidateList.bs.js";
import * as Core from "@material-ui/core";

function s(string) {
  return string;
}

function Home(Props) {
  var state = Props.state;
  var dispatch = Props.dispatch;
  var updateElectionName = function ($$event) {
    Curry._1(dispatch, {
          TAG: /* SetElectionName */0,
          _0: $$event.currentTarget.value
        });
  };
  return React.createElement("div", undefined, React.createElement(Core.TextField, {
                  id: "outlined-basic",
                  label: "Nom de l'élection",
                  onChange: updateElectionName,
                  value: state.electionName,
                  variant: "outlined"
                }), React.createElement(CandidateList.make, {
                  dispatch: dispatch,
                  state: state
                }), React.createElement(VoterList.make, {
                  state: state,
                  dispatch: dispatch
                }), React.createElement("br", undefined), React.createElement(Core.Button, {
                  children: "Create Election",
                  variant: "contained"
                }));
}

var make = Home;

export {
  s ,
  make ,
}
/* react Not a pure module */
