// Generated by ReScript, PLEASE EDIT WITH CARE


var base_url = process.env.NODE_ENV === "development" ? "https://scrutin-staging.fly.dev" : "https://api.scrutin.app";

var api_prefix = "/v0";

var api_url = base_url + api_prefix;

export {
  base_url ,
  api_prefix ,
  api_url ,
}
/* base_url Not a pure module */
