// Generated by ReScript, PLEASE EDIT WITH CARE


var api_url = process.env.NODE_ENV === "development" ? "http://localhost:8080" : "https://api.scrutin.app";

export {
  api_url ,
}
/* api_url Not a pure module */
