// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function _Admin_User_List(Props) {
  return React.createElement(React.Fragment, undefined);
}

var make = _Admin_User_List;

export {
  make ,
}
/* react Not a pure module */
