// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Admin_User_Show(Props) {
  return React.createElement(React.Fragment, undefined);
}

var make = Admin_User_Show;

export {
  make ,
}
/* react Not a pure module */
