// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Context from "../helpers/Context.bs.js";
import * as Ballot_New from "./Ballot_New.bs.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Belt_MapString from "rescript/lib/es6/belt_MapString.js";
import * as ReactNativePaper from "react-native-paper";

function Ballot_Show(Props) {
  var eventHash = Props.eventHash;
  var match = Context.use(undefined);
  var dispatch = match[1];
  var ballot = Belt_MapString.getExn(match[0].cached_ballots, eventHash);
  var ciphertext = Belt_Option.getWithDefault(ballot.ciphertext, "");
  return React.createElement(ReactNativePaper.List.Section, {
              title: "Ballot",
              children: null
            }, React.createElement(ReactNativePaper.List.Item, {
                  title: "Event Hash",
                  description: eventHash
                }), React.createElement(ReactNativePaper.List.Item, {
                  onPress: (function (param) {
                      Curry._1(dispatch, {
                            TAG: /* Navigate */0,
                            _0: {
                              TAG: /* Election_Show */0,
                              _0: ballot.electionTx
                            }
                          });
                    }),
                  title: "Election",
                  description: ballot.electionTx
                }), React.createElement(ReactNativePaper.List.Item, {
                  title: "Previous transaction",
                  description: Belt_Option.getWithDefault(ballot.previousTx, "")
                }), React.createElement(ReactNativePaper.List.Item, {
                  onPress: (function (param) {
                      Curry._1(dispatch, {
                            TAG: /* Navigate */0,
                            _0: {
                              TAG: /* Identity_Show */1,
                              _0: ballot.voterPublicKey
                            }
                          });
                    }),
                  title: "Voter",
                  description: ballot.voterPublicKey
                }), React.createElement(ReactNativePaper.List.Item, {
                  onPress: (function (param) {
                      Curry._1(dispatch, {
                            TAG: /* Navigate */0,
                            _0: {
                              TAG: /* Election_Show */0,
                              _0: ciphertext
                            }
                          });
                    }),
                  title: "Ciphertext",
                  description: ciphertext
                }), React.createElement(Ballot_New.make, {
                  ballotTx: eventHash
                }));
}

var make = Ballot_Show;

export {
  make ,
}
/* react Not a pure module */
