// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Ballot from "../state/Ballot.bs.js";
import * as Context from "../state/Context.bs.js";
import * as Belenios from "../helpers/Belenios.bs.js";
import * as Caml_obj from "rescript/lib/es6/caml_obj.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Transaction from "../state/Transaction.bs.js";
import * as Belt_MapString from "rescript/lib/es6/belt_MapString.js";
import * as ReactNativePaper from "react-native-paper";

function Ballot_New$Choice(Props) {
  var name = Props.name;
  var selected = Props.selected;
  var onSelect = Props.onSelect;
  return React.createElement(ReactNativePaper.List.Item, {
              onPress: (function (param) {
                  Curry._1(onSelect, undefined);
                }),
              title: name,
              left: (function (param) {
                  return React.createElement(ReactNativePaper.List.Icon, {
                              icon: selected ? "radiobox-marked" : "radiobox-blank"
                            });
                })
            });
}

var Choice = {
  make: Ballot_New$Choice
};

function Ballot_New(Props) {
  var ballotTx = Props.ballotTx;
  var match = Context.use(undefined);
  var dispatch = match[1];
  var state = match[0];
  var ballot = Belt_MapString.getExn(state.cache.ballots, ballotTx);
  var election = Belt_MapString.getExn(state.cache.elections, ballot.electionTx);
  var answers = Belenios.Election.answers(JSON.parse(election.params));
  var nbAnswers = answers.length;
  var match$1 = React.useState(function () {
        
      });
  var setChoice = match$1[1];
  var choice = match$1[0];
  var vote = function (param) {
    var selection = Belt_Array.mapWithIndex(Belt_Array.make(nbAnswers, 0), (function (i, _e) {
            if (Caml_obj.equal(choice, i)) {
              return 1;
            } else {
              return 0;
            }
          }));
    var ballot$1 = Ballot.make(ballot, election, selection);
    var owner = Belt_Option.getExn(Belt_Array.getBy(state.ids, (function (id) {
                return Belt_Array.some(ballot$1.owners, (function (owner) {
                              return owner === id.hexPublicKey;
                            }));
              })));
    var tx = Transaction.SignedBallot.make(ballot$1, owner);
    Curry._1(dispatch, {
          TAG: /* Transaction_Add */2,
          _0: tx
        });
  };
  return React.createElement(React.Fragment, undefined, React.createElement(ReactNativePaper.List.Section, {
                  title: "Choices",
                  children: Belt_Array.mapWithIndex(answers, (function (i, choiceName) {
                          var selected = Caml_obj.equal(choice, i);
                          return React.createElement(Ballot_New$Choice, {
                                      name: choiceName,
                                      selected: selected,
                                      onSelect: (function (param) {
                                          Curry._1(setChoice, (function (param) {
                                                  return i;
                                                }));
                                        }),
                                      key: String(i)
                                    });
                        }))
                }), React.createElement(ReactNativePaper.Button, {
                  mode: "contained",
                  onPress: vote,
                  children: "Voter"
                }));
}

var make = Ballot_New;

export {
  Choice ,
  make ,
}
/* react Not a pure module */
