// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Context from "../state/Context.bs.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Belt_MapString from "rescript/lib/es6/belt_MapString.js";
import * as Election_Booth from "./Election_Booth.bs.js";
import * as ReactNativePaper from "react-native-paper";

function Ballot_Show(Props) {
  var eventHash = Props.eventHash;
  var match = Context.use(undefined);
  var dispatch = match[1];
  var ballot = Belt_MapString.getExn(match[0].cache.ballots, eventHash);
  var ciphertext = Belt_Option.getWithDefault(ballot.ciphertext, "");
  return React.createElement(ReactNativePaper.List.Section, {
              title: "Ballot",
              children: null
            }, React.createElement(ReactNativePaper.List.Item, {
                  title: "Event Hash",
                  description: eventHash
                }), React.createElement(ReactNativePaper.List.Item, {
                  onPress: (function (param) {
                      Curry._1(dispatch, {
                            TAG: /* Navigate */0,
                            _0: {
                              TAG: /* Election_Show */0,
                              _0: ballot.electionTx
                            }
                          });
                    }),
                  title: "Election",
                  description: ballot.electionTx
                }), React.createElement(ReactNativePaper.List.Item, {
                  title: "Previous transaction",
                  description: Belt_Option.getWithDefault(ballot.previousTx, "")
                }), Belt_Array.mapWithIndex(ballot.owners, (function (i, publicKey) {
                    var onPress = function (param) {
                      Curry._1(dispatch, {
                            TAG: /* Navigate */0,
                            _0: {
                              TAG: /* Identity_Show */1,
                              _0: publicKey
                            }
                          });
                    };
                    var title = "Public Key " + String(i) + "";
                    return React.createElement(ReactNativePaper.List.Item, {
                                onPress: onPress,
                                title: title,
                                description: publicKey,
                                key: publicKey
                              });
                  })), React.createElement(ReactNativePaper.List.Item, {
                  onPress: (function (param) {
                      Curry._1(dispatch, {
                            TAG: /* Navigate */0,
                            _0: {
                              TAG: /* Election_Show */0,
                              _0: ciphertext
                            }
                          });
                    }),
                  title: "Ciphertext",
                  description: ciphertext
                }), React.createElement(Election_Booth.make, {
                  ballotTx: eventHash
                }));
}

var make = Ballot_Show;

export {
  make ,
}
/* react Not a pure module */
