// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";

function Candidate(Props) {
  var name = Props.name;
  var dispatch = Props.dispatch;
  var onClick = function (param) {
    Curry._1(dispatch, {
          TAG: /* RemoveVoter */2,
          _0: name
        });
  };
  return React.createElement("p", {
              key: name
            }, name, React.createElement("a", {
                  onClick: onClick
                }, "(remove)"));
}

var make = Candidate;

export {
  make ,
}
/* react Not a pure module */
