// Generated by ReScript, PLEASE EDIT WITH CARE

import * as X from "../helpers/X.bs.js";
import * as React from "react";
import * as Context from "../state/Context.bs.js";
import * as Belenios from "../helpers/Belenios.bs.js";
import * as Belt_MapString from "rescript/lib/es6/belt_MapString.js";
import * as ReactNativePaper from "react-native-paper";
import * as Election_Booth_ChoiceList from "./Election_Booth_ChoiceList.bs.js";

function Election_Booth(Props) {
  var ballotTx = Props.ballotTx;
  var match = Context.use(undefined);
  var state = match[0];
  var ballot = Belt_MapString.getExn(state.cache.ballots, ballotTx);
  var election = Belt_MapString.getExn(state.cache.elections, ballot.electionTx);
  Belenios.Election.answers(JSON.parse(election.params));
  var match$1 = React.useState(function () {
        return false;
      });
  var match$2 = React.useState(function () {
        
      });
  if (match$1[0]) {
    return React.createElement(ReactNativePaper.Title, {
                style: X.styles.title,
                children: null
              }, React.createElement(ReactNativePaper.Text, {
                    children: "Vote en cours..."
                  }), React.createElement(ReactNativePaper.ActivityIndicator, {}));
  } else {
    return React.createElement(React.Fragment, undefined, React.createElement(Election_Booth_ChoiceList.make, {
                    election: election,
                    choice: match$2[0],
                    setChoice: match$2[1]
                  }), React.createElement(ReactNativePaper.Button, {
                    children: "Voter"
                  }));
  }
}

var make = Election_Booth;

export {
  make ,
}
/* X Not a pure module */
