// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function ElectionBooth(Props) {
  return React.createElement(React.Fragment, undefined);
}

var make = ElectionBooth;

export {
  make ,
}
/* react Not a pure module */
