// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Context from "../state/Context.bs.js";
import * as Belt_MapString from "rescript/lib/es6/belt_MapString.js";
import * as Election_Booth from "./Election_Booth.bs.js";
import * as ReactNativePaper from "react-native-paper";

function Election_Show(Props) {
  var eventHash = Props.eventHash;
  var match = Context.use(undefined);
  var election = Belt_MapString.getExn(match[0].cache.elections, eventHash);
  return React.createElement(React.Fragment, undefined, React.createElement(ReactNativePaper.Title, {
                  children: "Owner"
                }), React.createElement(ReactNativePaper.Text, {
                  children: election.ownerPublicKey
                }), React.createElement(ReactNativePaper.Title, {
                  children: "Params"
                }), React.createElement(ReactNativePaper.Text, {
                  children: election.params
                }), React.createElement(ReactNativePaper.Title, {
                  children: "Trustees"
                }), React.createElement(ReactNativePaper.Text, {
                  children: election.trustees
                }), React.createElement(ReactNativePaper.Button, {
                  mode: "contained",
                  children: "Voter"
                }), React.createElement(Election_Booth.make, {
                  election: election
                }));
}

var make = Election_Show;

export {
  make ,
}
/* react Not a pure module */
