// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function ElectionNew_ChoiceItem(Props) {
  return React.createElement(React.Fragment, undefined);
}

var make = ElectionNew_ChoiceItem;

export {
  make ,
}
/* react Not a pure module */
