// Generated by ReScript, PLEASE EDIT WITH CARE

import * as X from "../helpers/X.bs.js";
import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as ReactNative from "react-native";
import * as ReactNativePaper from "react-native-paper";

function ElectionNew_ChoiceList$Item(Props) {
  var onRemove = Props.onRemove;
  var name = Props.name;
  return React.createElement(ReactNativePaper.List.Item, {
              onPress: (function (param) {
                  
                }),
              title: name,
              left: (function (param) {
                  return React.createElement(ReactNativePaper.List.Icon, {
                              icon: "vote"
                            });
                }),
              right: (function (param) {
                  return React.createElement(ReactNativePaper.Button, {
                              onPress: onRemove,
                              children: React.createElement(ReactNativePaper.List.Icon, {
                                    icon: "delete"
                                  })
                            });
                })
            });
}

var Item = {
  make: ElectionNew_ChoiceList$Item
};

function ElectionNew_ChoiceList(Props) {
  var choices = Props.choices;
  var setChoices = Props.setChoices;
  var match = React.useState(function () {
        return "";
      });
  var setName = match[1];
  var name = match[0];
  var match$1 = React.useState(function () {
        return false;
      });
  var setshowModal = match$1[1];
  var onSubmit = function (param) {
    Curry._1(setChoices, (function (choices) {
            return Belt_Array.concat(choices, [name]);
          }));
    Curry._1(setName, (function (param) {
            return "";
          }));
    Curry._1(setshowModal, (function (param) {
            return false;
          }));
  };
  return React.createElement(ReactNative.View, {
              testID: "choice-list",
              children: null
            }, React.createElement(X.Row.make, {
                  children: null
                }, React.createElement(X.Col.make, {
                      children: React.createElement(ReactNativePaper.Text, {
                            style: X.styles.title,
                            children: "Choix"
                          })
                    }), React.createElement(X.Col.make, {
                      children: React.createElement(ReactNativePaper.Text, {
                            children: ""
                          })
                    }), React.createElement(X.Col.make, {
                      children: React.createElement(ReactNativePaper.Button, {
                            mode: "contained",
                            onPress: (function (param) {
                                Curry._1(setshowModal, (function (param) {
                                        return true;
                                      }));
                              }),
                            children: "Ajouter"
                          })
                    })), React.createElement(ReactNative.View, {
                  children: Belt_Array.mapWithIndex(choices, (function (i, name) {
                          return React.createElement(ElectionNew_ChoiceList$Item, {
                                      onRemove: (function (param) {
                                          Curry._1(setChoices, (function (choices) {
                                                  return Belt_Array.keepWithIndex(choices, (function (_name, index) {
                                                                return index !== i;
                                                              }));
                                                }));
                                        }),
                                      name: name,
                                      key: String(i)
                                    });
                        }))
                }), React.createElement(ReactNativePaper.HelperText, {
                  style: X.styles.center,
                  visible: choices.length < 2,
                  type: "error",
                  children: "Il faut au moins 2 choix !"
                }), React.createElement(ReactNativePaper.Portal, {
                  children: React.createElement(ReactNativePaper.Modal, {
                        visible: match$1[0],
                        onDismiss: (function (param) {
                            Curry._1(setshowModal, (function (param) {
                                    return false;
                                  }));
                          }),
                        children: React.createElement(ReactNative.View, {
                              style: ReactNative.StyleSheet.flatten([
                                    X.styles.modal,
                                    X.styles.layout
                                  ]),
                              testID: "choice-modal",
                              children: null
                            }, React.createElement(ReactNativePaper.TextInput, {
                                  mode: "flat",
                                  autoFocus: true,
                                  label: "Nom du choix",
                                  value: name,
                                  onChangeText: (function (text) {
                                      Curry._1(setName, (function (param) {
                                              return text;
                                            }));
                                    }),
                                  onSubmitEditing: onSubmit,
                                  testID: "choice-name"
                                }), React.createElement(X.Row.make, {
                                  children: null
                                }, React.createElement(X.Col.make, {
                                      children: React.createElement(ReactNativePaper.Button, {
                                            onPress: (function (param) {
                                                Curry._1(setName, (function (param) {
                                                        return "";
                                                      }));
                                                Curry._1(setshowModal, (function (param) {
                                                        return false;
                                                      }));
                                              }),
                                            children: "Retour"
                                          })
                                    }), React.createElement(X.Col.make, {
                                      children: React.createElement(ReactNativePaper.Button, {
                                            mode: "contained",
                                            onPress: onSubmit,
                                            children: "Ajouter"
                                          })
                                    })))
                      })
                }));
}

var make = ElectionNew_ChoiceList;

export {
  Item ,
  make ,
}
/* X Not a pure module */
