// Generated by ReScript, PLEASE EDIT WITH CARE

import * as X from "../X.bs.js";
import * as Curry from "rescript/lib/es6/curry.js";
import * as State from "../state/State.bs.js";
import * as React from "react";
import * as ReactNative from "react-native";

function ElectionNew_VoterItem(Props) {
  var voter = Props.voter;
  var match = State.useContexts(undefined);
  var dispatch = match[1];
  return React.createElement(X.Row.make, {
              children: null
            }, React.createElement(X.Col.make, {
                  children: React.createElement(ReactNative.Text, {
                        children: voter.email
                      })
                }), React.createElement(X.Col.make, {
                  children: React.createElement(ReactNative.Button, {
                        color: "rosybrown",
                        onPress: (function (param) {
                            Curry._1(dispatch, {
                                  TAG: /* RemoveVoter */4,
                                  _0: voter.email
                                });
                          }),
                        title: "Remove"
                      })
                }));
}

var make = ElectionNew_VoterItem;

export {
  make ,
}
/* X Not a pure module */
