// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function ElectionBooth_ChoiceSelect(Props) {
  return React.createElement(React.Fragment, undefined);
}

var make = ElectionBooth_ChoiceSelect;

export {
  make ,
}
/* react Not a pure module */
