// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as State from "../state/State.bs.js";
import * as React from "react";
import * as ReactNative from "react-native";
import * as ReactNativePaper from "react-native-paper";

var styles = ReactNative.StyleSheet.create({
      "margin-x": {
        marginLeft: 15.0,
        marginRight: 15.0
      }
    });

function makeChoice(choice) {
  var match = React.useState(function () {
        return false;
      });
  var setChecked = match[1];
  var checked = match[0];
  return React.createElement(ReactNativePaper.List.Item, {
              onPress: (function (param) {
                  Curry._1(setChecked, (function (param) {
                          if (checked) {
                            return false;
                          } else {
                            return true;
                          }
                        }));
                }),
              title: choice.name,
              left: (function (param) {
                  return React.createElement(ReactNativePaper.List.Icon, {
                              icon: checked ? "checkbox-intermediate" : "checkbox-blank-outline"
                            });
                })
            });
}

function ElectionShow_ChoiceSelect(Props) {
  var match = State.useContextReducer(undefined);
  return React.createElement(ReactNative.View, {
              children: null
            }, React.createElement(ReactNativePaper.List.Section, {
                  title: "Choices",
                  children: match[0].election.choices.map(makeChoice),
                  style: styles["margin-x"]
                }), React.createElement(ReactNativePaper.Button, {
                  mode: "contained",
                  onPress: (function (param) {
                      
                    }),
                  children: "Voter"
                }));
}

var make = ElectionShow_ChoiceSelect;

export {
  styles ,
  makeChoice ,
  make ,
}
/* styles Not a pure module */
