// Generated by ReScript, PLEASE EDIT WITH CARE

import * as X from "../helpers/X.bs.js";
import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Config from "../helpers/Config.bs.js";
import * as Context from "../state/Context.bs.js";
import * as Identity from "../state/Identity.bs.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Transaction from "../state/Transaction.bs.js";
import * as Belt_MapString from "rescript/lib/es6/belt_MapString.js";
import * as ReactNativePaper from "react-native-paper";

function Election_Show(Props) {
  var eventHash = Props.eventHash;
  var match = Context.use(undefined);
  var dispatch = match[1];
  var state = match[0];
  var match$1 = React.useState(function () {
        return "";
      });
  var setEmail = match$1[1];
  var email = match$1[0];
  var election = Belt_MapString.getExn(state.cache.elections, eventHash);
  var publicKey = election.ownerPublicKey;
  var ballots = Belt_Array.keep(Belt_Array.keep(state.txs, (function (tx) {
              return tx.eventType === "ballot";
            })), (function (tx) {
          var ballot = Transaction.SignedBallot.unwrap(tx);
          return ballot.electionTx === eventHash;
        }));
  var nbBallots = ballots.length;
  var addBallot = function (param) {
    var id = Identity.make(undefined);
    var hexSecretKey = Belt_Option.getExn(id.hexSecretKey);
    var message = "\n      Hello !\n      Vous êtes invité à l'election.\n      Voici votre clé privée " + hexSecretKey + "\n      Pour information, la clé publique associée est " + id.hexPublicKey + "\n      L'organisateur vient de creer un bulletin de vote avec cette clé.\n    ";
    var dict = {};
    dict["email"] = email;
    dict["subject"] = "Vous êtes invité à un election";
    dict["text"] = message;
    X.post("" + Config.api_url + "/proxy_email", dict);
    var ballot_owners = [
      election.ownerPublicKey,
      id.hexPublicKey
    ];
    var ballot = {
      electionTx: eventHash,
      previousTx: undefined,
      owners: ballot_owners,
      ciphertext: undefined
    };
    var electionOwner = Belt_Option.getExn(Belt_Array.getBy(state.ids, (function (id) {
                return id.hexPublicKey === election.ownerPublicKey;
              })));
    var tx = Transaction.SignedBallot.make(ballot, electionOwner);
    Curry._1(dispatch, {
          TAG: /* Transaction_Add */2,
          _0: tx
        });
  };
  var onPress = function (param) {
    Curry._1(dispatch, {
          TAG: /* Navigate */0,
          _0: {
            TAG: /* Identity_Show */1,
            _0: publicKey
          }
        });
  };
  return React.createElement(React.Fragment, undefined, React.createElement(ReactNativePaper.List.Section, {
                  title: "Election",
                  children: null
                }, React.createElement(ReactNativePaper.List.Item, {
                      title: "Event Hash",
                      description: eventHash
                    }), React.createElement(ReactNativePaper.List.Item, {
                      onPress: onPress,
                      title: "Owner Public Key",
                      description: publicKey
                    }), React.createElement(ReactNativePaper.List.Item, {
                      title: "Params",
                      description: election.params
                    }), React.createElement(ReactNativePaper.List.Item, {
                      title: "Trustees",
                      description: election.trustees
                    })), React.createElement(ReactNativePaper.Divider, {}), React.createElement(ReactNativePaper.TextInput, {
                  mode: "flat",
                  label: "Email",
                  value: email,
                  onChangeText: (function (text) {
                      Curry._1(setEmail, (function (param) {
                              return text;
                            }));
                    })
                }), React.createElement(ReactNativePaper.Button, {
                  mode: "outlined",
                  onPress: addBallot,
                  children: "Add as voter"
                }), React.createElement(ReactNativePaper.Divider, {}), React.createElement(ReactNativePaper.List.Section, {
                  title: "" + String(nbBallots) + " ballots",
                  children: Belt_Array.map(ballots, (function (tx) {
                          Transaction.SignedBallot.unwrap(tx);
                          return React.createElement(ReactNativePaper.List.Item, {
                                      onPress: (function (param) {
                                          Curry._1(dispatch, {
                                                TAG: /* Navigate */0,
                                                _0: {
                                                  TAG: /* Ballot_Show */2,
                                                  _0: tx.eventHash
                                                }
                                              });
                                        }),
                                      title: "Ballot " + tx.eventHash + "",
                                      key: tx.eventHash
                                    });
                        }))
                }));
}

var make = Election_Show;

export {
  make ,
}
/* X Not a pure module */
