// Generated by ReScript, PLEASE EDIT WITH CARE

import * as X from "../X.bs.js";
import * as Curry from "rescript/lib/es6/curry.js";
import * as State from "../state/State.bs.js";
import * as React from "react";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as ReactNative from "react-native";
import * as ReactNativePaper from "react-native-paper";

function ElectionShow(Props) {
  var match = State.useContexts(undefined);
  var dispatch = match[1];
  var state = match[0];
  React.useState(function () {
        return state.ballot.token;
      });
  React.useState(function () {
        return /* Blank */0;
      });
  var nb_ballots = String(state.election.ballots.length);
  var nb_votes = String(Belt_Array.keep(state.election.ballots, (function (ballot) {
              return ballot.ciphertext === "";
            })).length);
  return React.createElement(ReactNative.View, {
              children: null
            }, React.createElement(ReactNativePaper.Title, {
                  style: X.styles.title,
                  children: state.election.name
                }), React.createElement(ReactNativePaper.Title, {
                  style: X.styles.subtitle,
                  children: "" + nb_ballots + "/" + nb_votes + " voted"
                }), React.createElement(ReactNative.View, {
                  style: X.styles.separator
                }), React.createElement(ReactNative.View, {
                  style: X.styles.row,
                  children: null
                }, React.createElement(ReactNative.View, {
                      style: X.styles.col,
                      children: React.createElement(ReactNativePaper.Button, {
                            onPress: (function (param) {
                                Curry._1(dispatch, {
                                      TAG: /* Navigate */11,
                                      _0: {
                                        TAG: /* ElectionBooth */1,
                                        _0: state.election.id
                                      }
                                    });
                              }),
                            children: "Vote"
                          })
                    }), React.createElement(ReactNative.View, {
                      style: X.styles.col,
                      children: React.createElement(ReactNativePaper.Button, {
                            onPress: (function (param) {
                                
                              }),
                            children: "Close"
                          })
                    })));
}

var make = ElectionShow;

export {
  make ,
}
/* X Not a pure module */
