// Generated by ReScript, PLEASE EDIT WITH CARE

import * as X from "../helpers/X.bs.js";
import * as React from "react";
import * as Belenios from "../helpers/Belenios.bs.js";
import * as ReactNativePaper from "react-native-paper";
import * as Election_Booth_ChoiceList from "./Election_Booth_ChoiceList.bs.js";

function Election_Booth(Props) {
  var election = Props.election;
  Belenios.Election.answers(JSON.parse(election.params));
  var match = React.useState(function () {
        return false;
      });
  var match$1 = React.useState(function () {
        
      });
  if (match[0]) {
    return React.createElement(ReactNativePaper.Title, {
                style: X.styles.title,
                children: null
              }, React.createElement(ReactNativePaper.Text, {
                    children: "Vote en cours..."
                  }), React.createElement(ReactNativePaper.ActivityIndicator, {}));
  } else {
    return React.createElement(React.Fragment, undefined, React.createElement(Election_Booth_ChoiceList.make, {
                    election: election,
                    choice: match$1[0],
                    setChoice: match$1[1]
                  }), React.createElement(ReactNativePaper.Button, {
                    children: "Voter"
                  }));
  }
}

var make = Election_Booth;

export {
  make ,
}
/* X Not a pure module */
