// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function ElectionNew_VoterList(Props) {
  return React.createElement(React.Fragment, undefined);
}

var make = ElectionNew_VoterList;

export {
  make ,
}
/* react Not a pure module */
