// Generated by ReScript, PLEASE EDIT WITH CARE

import * as X from "../helpers/X.bs.js";
import * as React from "react";
import * as Belenios from "../helpers/Belenios.bs.js";
import * as ReactNativePaper from "react-native-paper";

function Election_Booth(Props) {
  var election = Props.election;
  Belenios.Election.answers(JSON.parse(election.params));
  var match = React.useState(function () {
        return false;
      });
  React.useState(function () {
        
      });
  if (match[0]) {
    return React.createElement(ReactNativePaper.Title, {
                style: X.styles.title,
                children: null
              }, React.createElement(ReactNativePaper.Text, {
                    children: "Vote en cours..."
                  }), React.createElement(ReactNativePaper.ActivityIndicator, {}));
  } else {
    return React.createElement(React.Fragment, undefined);
  }
}

var make = Election_Booth;

export {
  make ,
}
/* X Not a pure module */
