// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as ReactNativePaper from "react-native-paper";
import * as Election_New_ChoiceList from "./Election_New_ChoiceList.bs.js";

function Election_New(Props) {
  var match = React.useState(function () {
        return "";
      });
  var setName = match[1];
  var match$1 = React.useState(function () {
        return "";
      });
  var setDesc = match$1[1];
  var match$2 = React.useState(function () {
        return "";
      });
  var setChoices = match$2[1];
  return React.createElement(React.Fragment, undefined, React.createElement(ReactNativePaper.TextInput, {
                  mode: "flat",
                  label: "Nom de l'élection",
                  value: match[0],
                  onChangeText: (function (text) {
                      Curry._1(setName, (function (param) {
                              return text;
                            }));
                    }),
                  testID: "election-name"
                }), React.createElement(ReactNativePaper.TextInput, {
                  mode: "flat",
                  label: "Description",
                  value: match$1[0],
                  onChangeText: (function (text) {
                      Curry._1(setDesc, (function (param) {
                              return text;
                            }));
                    }),
                  testID: "election-desc"
                }), React.createElement(Election_New_ChoiceList.make, {
                  onUpdate: (function (choices) {
                      Curry._1(setChoices, (function (param) {
                              return choices;
                            }));
                    })
                }));
}

var make = Election_New;

export {
  make ,
}
/* react Not a pure module */
