// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Context from "../helpers/Context.bs.js";
import * as ReactNativePaper from "react-native-paper";

function Header(Props) {
  var match = Context.use(undefined);
  var dispatch = match[1];
  return React.createElement(ReactNativePaper.Appbar.Header, {
              children: null
            }, React.createElement(ReactNativePaper.Appbar.Action, {
                  icon: "home",
                  onPress: (function (param) {
                      Curry._1(dispatch, {
                            TAG: /* Navigate */0,
                            _0: /* Home_Elections */0
                          });
                    })
                }), React.createElement(ReactNativePaper.Appbar.Content, {
                  title: "Verifiable secret voting"
                }), React.createElement(ReactNativePaper.Appbar.Action, {
                  icon: "cog-outline",
                  onPress: (function (param) {
                      Curry._1(dispatch, {
                            TAG: /* Navigate */0,
                            _0: /* Settings */5
                          });
                    })
                }));
}

var make = Header;

export {
  make ,
}
/* react Not a pure module */
