// Generated by ReScript, PLEASE EDIT WITH CARE

import * as X from "../helpers/X.bs.js";
import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Context from "../state/Context.bs.js";
import * as Identity from "../state/Identity.bs.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as ReactNativePaper from "react-native-paper";

function Home_Identities(Props) {
  var match = Context.use(undefined);
  var dispatch = match[1];
  return React.createElement(React.Fragment, undefined, React.createElement(X.Title.make, {
                  children: "Identités"
                }), React.createElement(ReactNativePaper.List.Section, {
                  title: "",
                  children: Belt_Array.map(match[0].ids, (function (id) {
                          return React.createElement(ReactNativePaper.List.Item, {
                                      onPress: (function (param) {
                                          Curry._1(dispatch, {
                                                TAG: /* Navigate */0,
                                                _0: {
                                                  TAG: /* Identity_Show */1,
                                                  _0: id.hexPublicKey
                                                }
                                              });
                                        }),
                                      title: "0x" + id.hexPublicKey,
                                      key: id.hexPublicKey
                                    });
                        })),
                  style: X.styles["margin-x"]
                }), React.createElement(ReactNativePaper.Button, {
                  mode: "contained",
                  onPress: (function (param) {
                      Curry._1(dispatch, {
                            TAG: /* Identity_Add */1,
                            _0: Identity.make(undefined)
                          });
                    }),
                  children: "New identity"
                }), React.createElement(ReactNativePaper.Button, {
                  mode: "outlined",
                  onPress: (function (param) {
                      Identity.clear(undefined);
                    }),
                  children: "Clear identities"
                }));
}

var make = Home_Identities;

export {
  make ,
}
/* X Not a pure module */
