// Generated by ReScript, PLEASE EDIT WITH CARE

import * as X from "../helpers/X.bs.js";
import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Context from "../state/Context.bs.js";
import * as ReactNativePaper from "react-native-paper";

function Home(Props) {
  var match = Context.use(undefined);
  var dispatch = match[1];
  return React.createElement(React.Fragment, undefined, React.createElement(X.Title.make, {
                  children: "Identités"
                }), React.createElement(ReactNativePaper.List.Section, {
                  title: "",
                  children: React.createElement(React.Fragment, undefined),
                  style: X.styles["margin-x"]
                }), React.createElement(ReactNativePaper.Button, {
                  mode: "outlined",
                  onPress: (function (param) {
                      Curry._1(dispatch, /* Identity_Generate */1);
                    }),
                  children: "Create a new identity"
                }), React.createElement(X.Title.make, {
                  children: "Transactions"
                }), React.createElement(ReactNativePaper.List.Section, {
                  title: "",
                  children: React.createElement(React.Fragment, undefined),
                  style: X.styles["margin-x"]
                }), React.createElement(X.Title.make, {
                  children: "Elections"
                }), React.createElement(X.Title.make, {
                  children: "Ballots"
                }), React.createElement(X.Title.make, {
                  children: "Trustees"
                }));
}

var make = Home;

export {
  make ,
}
/* X Not a pure module */
