// Generated by ReScript, PLEASE EDIT WITH CARE

import * as X from "../X.bs.js";
import * as Curry from "rescript/lib/es6/curry.js";
import * as State from "../state/State.bs.js";
import * as React from "react";
import * as ReactNativePaper from "react-native-paper";

function electionLink(election) {
  var match = State.useContextReducer(undefined);
  var dispatch = match[1];
  return React.createElement(ReactNativePaper.List.Item, {
              onPress: (function (param) {
                  Curry._1(dispatch, {
                        TAG: /* Navigate */10,
                        _0: /* ElectionShow */{
                          _0: election.id
                        }
                      });
                }),
              title: election.name,
              left: (function (param) {
                  return React.createElement(ReactNativePaper.List.Icon, {
                              icon: "vote"
                            });
                })
            });
}

function Home_ElectionList(Props) {
  var match = State.useContextReducer(undefined);
  var state = match[0];
  if (state.elections_loading) {
    return React.createElement(ReactNativePaper.ActivityIndicator, {});
  } else {
    return React.createElement(ReactNativePaper.List.Section, {
                title: "Elections en cours",
                children: state.elections.map(electionLink),
                style: X.styles["margin-x"]
              });
  }
}

var make = Home_ElectionList;

export {
  electionLink ,
  make ,
}
/* X Not a pure module */
