// Generated by ReScript, PLEASE EDIT WITH CARE

import * as X from "../helpers/X.bs.js";
import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Context from "../state/Context.bs.js";
import * as Identity from "../state/Identity.bs.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as ReactNativePaper from "react-native-paper";

function Home(Props) {
  var match = Context.use(undefined);
  var dispatch = match[1];
  var genIdentity = function (param) {
    Curry._1(dispatch, {
          TAG: /* Identity_Add */1,
          _0: Identity.make(undefined)
        });
  };
  return React.createElement(React.Fragment, undefined, React.createElement(X.Title.make, {
                  children: "Identités"
                }), React.createElement(ReactNativePaper.List.Section, {
                  title: "",
                  children: Belt_Array.map(match[0].identities, (function (identity) {
                          return React.createElement(ReactNativePaper.List.Item, {
                                      title: "0x" + identity.hexPublicKey,
                                      key: identity.hexPublicKey
                                    });
                        })),
                  style: X.styles["margin-x"]
                }), React.createElement(ReactNativePaper.Button, {
                  mode: "outlined",
                  onPress: genIdentity,
                  children: "Generate identity"
                }), React.createElement(ReactNativePaper.Button, {
                  mode: "outlined",
                  onPress: (function (param) {
                      Identity.clear(undefined);
                    }),
                  children: "Clear identities"
                }), React.createElement(X.Title.make, {
                  children: "Elections"
                }), React.createElement(ReactNativePaper.Button, {
                  mode: "contained",
                  onPress: (function (param) {
                      Curry._1(dispatch, {
                            TAG: /* Navigate */0,
                            _0: /* Election_New */1
                          });
                    }),
                  children: "New election"
                }), React.createElement(X.Title.make, {
                  children: "Ballots"
                }), React.createElement(X.Title.make, {
                  children: "Trustees"
                }), React.createElement(X.Title.make, {
                  children: "Transactions"
                }), React.createElement(ReactNativePaper.List.Section, {
                  title: "",
                  children: React.createElement(React.Fragment, undefined),
                  style: X.styles["margin-x"]
                }));
}

var make = Home;

export {
  make ,
}
/* X Not a pure module */
