// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Context from "../state/Context.bs.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Belt_MapString from "rescript/lib/es6/belt_MapString.js";
import * as ReactNativePaper from "react-native-paper";

function Identity_Show(Props) {
  var publicKey = Props.publicKey;
  var match = Context.use(undefined);
  var dispatch = match[1];
  return React.createElement(React.Fragment, undefined, React.createElement(ReactNativePaper.Title, {
                  children: "Identity"
                }), React.createElement(ReactNativePaper.Text, {
                  children: publicKey
                }), React.createElement(ReactNativePaper.Title, {
                  children: "My Elections (as admin)"
                }), Belt_Array.map(Belt_MapString.toArray(Belt_MapString.keep(match[0].cache.elections, (function (eventHash, election) {
                            return election.ownerPublicKey === publicKey;
                          }))), (function (param) {
                    var eventHash = param[0];
                    return React.createElement(ReactNativePaper.Text, {
                                onPress: (function (param) {
                                    Curry._1(dispatch, {
                                          TAG: /* Navigate */0,
                                          _0: {
                                            TAG: /* Election_Show */0,
                                            _0: eventHash
                                          }
                                        });
                                  }),
                                children: eventHash
                              });
                  })), React.createElement(ReactNativePaper.Title, {
                  children: "My Elections (as voter)"
                }), React.createElement(ReactNativePaper.Title, {
                  children: "My Elections (as trustee)"
                }), React.createElement(ReactNativePaper.Title, {
                  children: "Elections (as voter)"
                }));
}

var make = Identity_Show;

export {
  make ,
}
/* react Not a pure module */
