// Generated by ReScript, PLEASE EDIT WITH CARE

import * as X from "../helpers/X.bs.js";
import * as React from "react";
import * as Context from "../Context.bs.js";
import * as ReactNative from "react-native";
import * as ReactNativePaper from "react-native-paper";

function Layout(Props) {
  var state = Props.state;
  var dispatch = Props.dispatch;
  var children = Props.children;
  return React.createElement(ReactNativePaper.Provider, {
              children: React.createElement(Context.State.Provider.make, {
                    value: state,
                    children: React.createElement(Context.Dispatch.Provider.make, {
                          value: dispatch,
                          children: React.createElement(ReactNative.SafeAreaView, {
                                style: X.styles.layout,
                                children: React.createElement(ReactNative.ScrollView, {
                                      children: children
                                    })
                              })
                        })
                  }),
              theme: {
                dark: true
              }
            });
}

var make = Layout;

export {
  make ,
}
/* X Not a pure module */
