// Generated by ReScript, PLEASE EDIT WITH CARE

import * as X from "../X.bs.js";
import * as User from "../state/User.bs.js";
import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Config from "../Config.bs.js";
import * as Context from "../state/Context.bs.js";
import * as ReactNative from "react-native";
import * as ReactNativePaper from "react-native-paper";

function Login(Props) {
  var match = Context.use(undefined);
  var dispatch = match[1];
  var match$1 = React.useState(function () {
        return "";
      });
  var setEmail = match$1[1];
  var email = match$1[0];
  var match$2 = React.useState(function () {
        return "";
      });
  var setPassword = match$2[1];
  var password = match$2[0];
  var match$3 = React.useState(function () {
        return "";
      });
  var setError = match$3[1];
  var error = match$3[0];
  var onSubmit = function (param) {
    var user = {
      email: email,
      password: password
    };
    X.post("" + Config.api_url + "/signin", User.to_json(user)).then(function (prim) {
            return prim.status;
          }).then(function (status) {
          if (status === 200) {
            return Curry._1(dispatch, {
                        TAG: /* User_Login */12,
                        _0: user
                      });
          } else {
            return Curry._1(setError, (function (param) {
                          return "Error login in";
                        }));
          }
        });
  };
  return React.createElement(ReactNative.View, {
              style: X.styles["margin-x"],
              children: null
            }, React.createElement(ReactNativePaper.Title, {
                  style: X.styles.title,
                  children: "Login"
                }), error === "" ? React.createElement(React.Fragment, undefined) : React.createElement(ReactNativePaper.HelperText, {
                    type: "error",
                    children: error
                  }), React.createElement(ReactNativePaper.TextInput, {
                  mode: "flat",
                  label: "Username",
                  value: email,
                  onChangeText: (function (text) {
                      Curry._1(setEmail, (function (param) {
                              return text;
                            }));
                    })
                }), React.createElement(ReactNativePaper.TextInput, {
                  mode: "flat",
                  label: "Password",
                  secureTextEntry: true,
                  value: password,
                  onChangeText: (function (text) {
                      Curry._1(setPassword, (function (param) {
                              return text;
                            }));
                    })
                }), React.createElement(ReactNativePaper.Divider, {}), React.createElement(ReactNativePaper.Button, {
                  mode: "contained",
                  style: X.styles["margin-x"],
                  onPress: onSubmit,
                  children: "Login"
                }));
}

var make = Login;

export {
  make ,
}
/* X Not a pure module */
