// Generated by ReScript, PLEASE EDIT WITH CARE

import * as X from "../X.bs.js";
import * as User from "../state/User.bs.js";
import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Config from "../Config.bs.js";
import * as Context from "../state/Context.bs.js";
import * as Js_dict from "rescript/lib/es6/js_dict.js";
import * as Js_json from "rescript/lib/es6/js_json.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as ReactNative from "react-native";
import * as ReactNativePaper from "react-native-paper";

function Login(Props) {
  var match = Context.use(undefined);
  var dispatch = match[1];
  var match$1 = React.useState(function () {
        return "";
      });
  var setEmail = match$1[1];
  var email = match$1[0];
  var match$2 = React.useState(function () {
        return "";
      });
  var setPassword = match$2[1];
  var password = match$2[0];
  var match$3 = React.useState(function () {
        return "";
      });
  var setError = match$3[1];
  var error = match$3[0];
  var onSubmit = function (param) {
    var user = {
      id: undefined,
      email: email,
      password: password
    };
    X.post("" + Config.api_url + "/signin", User.to_json(user)).then(function (response) {
          var status = response.status;
          return response.json().then(function (content) {
                      if (status !== 200) {
                        return Curry._1(setError, (function (param) {
                                      return "Error login in";
                                    }));
                      }
                      var dict = Belt_Option.getExn(Js_json.decodeObject(content));
                      var id = Belt_Option.map(Belt_Option.flatMap(Js_dict.get(dict, "id"), Js_json.decodeNumber), (function (prim) {
                              return prim | 0;
                            }));
                      console.log(Js_dict.get(dict, "id"));
                      console.log(Belt_Option.flatMap(Js_dict.get(dict, "id"), Js_json.decodeNumber));
                      console.log(Belt_Option.map(Belt_Option.flatMap(Js_dict.get(dict, "id"), Js_json.decodeNumber), (function (prim) {
                                  return prim | 0;
                                })));
                      Curry._1(dispatch, {
                            TAG: /* User_Login */13,
                            _0: {
                              id: id,
                              email: email,
                              password: password
                            }
                          });
                    });
        });
  };
  return React.createElement(ReactNative.View, {
              style: X.styles["margin-x"],
              children: null
            }, React.createElement(ReactNativePaper.Title, {
                  style: X.styles.title,
                  children: "Please login (only beta-testers can create elections)"
                }), error === "" ? React.createElement(React.Fragment, undefined) : React.createElement(ReactNativePaper.HelperText, {
                    type: "error",
                    children: error
                  }), React.createElement(ReactNativePaper.TextInput, {
                  mode: "flat",
                  label: "Username",
                  value: email,
                  onChangeText: (function (text) {
                      Curry._1(setEmail, (function (param) {
                              return text;
                            }));
                    }),
                  testID: "login-username"
                }), React.createElement(ReactNativePaper.TextInput, {
                  mode: "flat",
                  label: "Password",
                  secureTextEntry: true,
                  value: password,
                  onChangeText: (function (text) {
                      Curry._1(setPassword, (function (param) {
                              return text;
                            }));
                    }),
                  onSubmitEditing: onSubmit,
                  testID: "login-password"
                }), React.createElement(ReactNativePaper.Divider, {}), React.createElement(ReactNativePaper.Button, {
                  mode: "contained",
                  style: X.styles["margin-x"],
                  onPress: onSubmit,
                  children: "Login"
                }));
}

var make = Login;

export {
  make ,
}
/* X Not a pure module */
