// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Context from "../Context.bs.js";
import * as ReactNativePaper from "react-native-paper";

function Navigation(Props) {
  var match = Context.use(undefined);
  var dispatch = match[1];
  var match$1 = match[0].route;
  var index;
  if (typeof match$1 === "number") {
    switch (match$1) {
      case /* Home_Trustees */1 :
          index = 2;
          break;
      case /* Home_Identities */2 :
          index = 1;
          break;
      case /* Home_Transactions */3 :
          index = 3;
          break;
      case /* Home_Elections */0 :
      case /* Election_New */4 :
          index = 0;
          break;
      
    }
  } else {
    index = 0;
  }
  return React.createElement(ReactNativePaper.BottomNavigation, {
              onIndexChange: (function (i) {
                  switch (i) {
                    case 0 :
                        return Curry._1(dispatch, {
                                    TAG: /* Navigate */0,
                                    _0: /* Home_Elections */0
                                  });
                    case 1 :
                        return Curry._1(dispatch, {
                                    TAG: /* Navigate */0,
                                    _0: /* Home_Identities */2
                                  });
                    case 2 :
                        return Curry._1(dispatch, {
                                    TAG: /* Navigate */0,
                                    _0: /* Home_Trustees */1
                                  });
                    case 3 :
                        return Curry._1(dispatch, {
                                    TAG: /* Navigate */0,
                                    _0: /* Home_Transactions */3
                                  });
                    default:
                      return ;
                  }
                }),
              renderScene: (function (o) {
                  return React.createElement(ReactNativePaper.Text, {
                              children: o.route.title
                            });
                }),
              navigationState: {
                index: index,
                routes: [
                  {
                    key: "elections",
                    title: "Elections",
                    icon: "vote",
                    accessibilityLabel: undefined,
                    badge: undefined,
                    color: undefined,
                    testID: undefined
                  },
                  {
                    key: "identities",
                    title: "Identities",
                    icon: "account",
                    accessibilityLabel: undefined,
                    badge: undefined,
                    color: undefined,
                    testID: undefined
                  },
                  {
                    key: "trustees",
                    title: "Trustees",
                    icon: "thing",
                    accessibilityLabel: undefined,
                    badge: undefined,
                    color: undefined,
                    testID: undefined
                  },
                  {
                    key: "transactions",
                    title: "Transactions",
                    icon: "thing",
                    accessibilityLabel: undefined,
                    badge: undefined,
                    color: undefined,
                    testID: undefined
                  }
                ]
              }
            });
}

var make = Navigation;

export {
  make ,
}
/* react Not a pure module */
