// Generated by ReScript, PLEASE EDIT WITH CARE

import * as X from "../helpers/X.bs.js";
import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Context from "../helpers/Context.bs.js";
import * as ReactNativePaper from "react-native-paper";

function Settings_View(Props) {
  var match = Context.use(undefined);
  var dispatch = match[1];
  return React.createElement(ReactNativePaper.List.Section, {
              title: "Internals",
              children: null,
              style: X.styles["margin-x"]
            }, React.createElement(ReactNativePaper.List.Item, {
                  onPress: (function (param) {
                      Curry._1(dispatch, {
                            TAG: /* Navigate */0,
                            _0: /* Home_Identities */2
                          });
                    }),
                  title: "Identities"
                }), React.createElement(ReactNativePaper.List.Item, {
                  onPress: (function (param) {
                      Curry._1(dispatch, {
                            TAG: /* Navigate */0,
                            _0: /* Home_Trustees */1
                          });
                    }),
                  title: "Trustees"
                }), React.createElement(ReactNativePaper.List.Item, {
                  onPress: (function (param) {
                      Curry._1(dispatch, {
                            TAG: /* Navigate */0,
                            _0: /* Contact_Index */4
                          });
                    }),
                  title: "Contacts"
                }), React.createElement(ReactNativePaper.List.Item, {
                  onPress: (function (param) {
                      Curry._1(dispatch, {
                            TAG: /* Navigate */0,
                            _0: /* Home_Transactions */3
                          });
                    }),
                  title: "Transactions"
                }));
}

var make = Settings_View;

export {
  make ,
}
/* X Not a pure module */
