// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Context from "../helpers/Context.bs.js";
import * as Trustee from "../model/Trustee.bs.js";
import * as Belenios from "../helpers/Belenios.bs.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as ReactNativePaper from "react-native-paper";

function Trustee_Home(Props) {
  var match = Context.use(undefined);
  return React.createElement(ReactNativePaper.List.Section, {
              title: "Trustees",
              children: null
            }, Belt_Array.map(match[0].trustees, (function (trustee) {
                    var privkey = trustee.privkey;
                    var pubkey = Belenios.Trustees.pubkey(trustee.trustees);
                    return React.createElement(ReactNativePaper.List.Item, {
                                title: pubkey,
                                description: privkey,
                                key: pubkey
                              });
                  })), React.createElement(ReactNativePaper.Button, {
                  mode: "outlined",
                  onPress: (function (param) {
                      Trustee.clear(undefined);
                    }),
                  children: "Clear"
                }));
}

var make = Trustee_Home;

export {
  make ,
}
/* react Not a pure module */
