// Generated by ReScript, PLEASE EDIT WITH CARE

import * as X from "../X.bs.js";
import * as React from "react";
import * as Context from "../state/Context.bs.js";
import * as ReactNative from "react-native";
import * as ReactNativePaper from "react-native-paper";

function User_Signin(Props) {
  Context.use(undefined);
  return React.createElement(ReactNative.View, {
              children: React.createElement(ReactNativePaper.Button, {
                    mode: "contained",
                    style: X.styles["margin-x"],
                    onPress: (function (param) {
                        
                      }),
                    children: "Signin"
                  })
            });
}

var make = User_Signin;

export {
  make ,
}
/* X Not a pure module */
