// Generated by ReScript, PLEASE EDIT WITH CARE

import * as X from "../X.bs.js";
import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Context from "../state/Context.bs.js";
import * as ReactNative from "react-native";
import * as ReactNativePaper from "react-native-paper";

function User_Login_Obselete(Props) {
  Context.use(undefined);
  var match = React.useState(function () {
        return "";
      });
  var setEmail = match[1];
  var match$1 = React.useState(function () {
        return "";
      });
  var error = match$1[0];
  var onSubmit = function (param) {
    
  };
  return React.createElement(ReactNative.View, {
              style: X.styles["margin-x"],
              children: null
            }, React.createElement(ReactNativePaper.Title, {
                  style: X.styles.title,
                  children: "Enter your email to join..."
                }), error === "" ? React.createElement(React.Fragment, undefined) : React.createElement(ReactNativePaper.HelperText, {
                    type: "error",
                    children: error
                  }), React.createElement(ReactNativePaper.TextInput, {
                  mode: "flat",
                  label: "Email",
                  value: match[0],
                  onChangeText: (function (text) {
                      Curry._1(setEmail, (function (param) {
                              return text;
                            }));
                    }),
                  testID: "login-email"
                }), React.createElement(ReactNativePaper.Divider, {}), React.createElement(ReactNativePaper.Button, {
                  mode: "contained",
                  style: X.styles["margin-x"],
                  onPress: onSubmit,
                  children: "Continue"
                }));
}

var make = User_Login_Obselete;

export {
  make ,
}
/* X Not a pure module */
