// Generated by ReScript, PLEASE EDIT WITH CARE

import * as X from "../X.bs.js";
import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Context from "../state/Context.bs.js";
import * as ReactNativePaper from "react-native-paper";

function User_Register(Props) {
  var match = React.useState(function () {
        return "";
      });
  var setEmail = match[1];
  var match$1 = React.useState(function () {
        return false;
      });
  var setLoading = match$1[1];
  return React.createElement(React.Fragment, undefined, React.createElement(ReactNativePaper.Title, {
                  style: X.styles.center,
                  children: "Ready to vote ?"
                }), React.createElement(ReactNativePaper.TextInput, {
                  mode: "flat",
                  label: "Email",
                  value: match[0],
                  onChangeText: (function (text) {
                      Curry._1(setEmail, (function (param) {
                              return text;
                            }));
                    }),
                  testID: "email-input"
                }), React.createElement(ReactNativePaper.Button, {
                  mode: "contained",
                  onPress: (function (param) {
                      Curry._1(setLoading, (function (param) {
                              return true;
                            }));
                      Context.dispatch({
                            TAG: /* Navigate */12,
                            _0: /* User_Register_Confirm */4
                          });
                    }),
                  children: match$1[0] ? "Loading..." : "Next"
                }));
}

var make = User_Register;

export {
  make ,
}
/* X Not a pure module */
