// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";

function VoterList(Props) {
  var state = Props.state;
  var dispatch = Props.dispatch;
  var match = React.useState(function () {
        return "";
      });
  var setVoterName = match[1];
  var voterName = match[0];
  var voterEl = function (voter) {
    var onClick = function (param) {
      Curry._1(dispatch, {
            TAG: /* RemoveVoter */2,
            _0: voter
          });
    };
    return React.createElement("p", {
                key: voter
              }, voter, React.createElement("a", {
                    onClick: onClick
                  }, "(remove)"));
  };
  var addVoter = function (param) {
    Curry._1(dispatch, {
          TAG: /* AddVoter */1,
          _0: voterName
        });
    Curry._1(setVoterName, (function (param) {
            return "";
          }));
  };
  var onKeyDown = function ($$event) {
    if ($$event.key === "Enter") {
      return addVoter(undefined);
    }
    
  };
  var updateVoterName = function ($$event) {
    Curry._1(setVoterName, $$event.currentTarget.value);
  };
  return React.createElement("div", undefined, React.createElement("h1", undefined, "VoterList"), React.createElement("br", undefined), state.voters.map(voterEl), React.createElement("br", undefined), "Add a new voter:", React.createElement("br", undefined), React.createElement("input", {
                  onKeyDown: onKeyDown,
                  onChange: updateVoterName
                }), React.createElement("a", {
                  onClick: addVoter
                }, "(add)"), React.createElement("br", undefined));
}

var make = VoterList;

export {
  make ,
}
/* react Not a pure module */
