// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Json_Decode$JsonCombinators from "rescript-json-combinators/src/Json_Decode.bs.js";

var from_json = Json_Decode$JsonCombinators.object(function (field) {
      return {
              choiceId: field.optional("choice_id", Json_Decode$JsonCombinators.$$int),
              token: field.required("hashed_token", Json_Decode$JsonCombinators.string)
            };
    });

function to_json(r) {
  return {
          choice_id: r.choiceId,
          token: r.token
        };
}

var initial = {
  choiceId: undefined,
  token: ""
};

export {
  initial ,
  from_json ,
  to_json ,
}
/* from_json Not a pure module */
