// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Json_Decode$JsonCombinators from "rescript-json-combinators/src/Json_Decode.bs.js";
import * as Json_Encode$JsonCombinators from "rescript-json-combinators/src/Json_Encode.bs.js";

var from_json = Json_Decode$JsonCombinators.object(function (field) {
      var electionId = field.optional("election_id", Json_Decode$JsonCombinators.$$int);
      return {
              electionId: Belt_Option.getWithDefault(electionId, 0),
              ciphertext: field.required("ciphertext", Json_Decode$JsonCombinators.option(Json_Decode$JsonCombinators.string)),
              private_credential: Belt_Option.getWithDefault(field.optional("private_credential", Json_Decode$JsonCombinators.string), ""),
              public_credential: field.required("public_credential", Json_Decode$JsonCombinators.string)
            };
    });

function to_json(r) {
  return {
          election_id: r.electionId,
          ciphertext: Json_Encode$JsonCombinators.option((function (prim) {
                  return prim;
                }), r.ciphertext),
          public_credential: r.public_credential,
          private_credential: r.private_credential
        };
}

var initial = {
  electionId: 0,
  ciphertext: undefined,
  private_credential: "",
  public_credential: ""
};

export {
  initial ,
  from_json ,
  to_json ,
}
/* from_json Not a pure module */
