// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as Store from "./Store.bs.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";

function fetchIdentities(dispatch) {
  Store.Identities.get(undefined).then(function (ids) {
        return Belt_Array.map(ids, (function (id) {
                      return Curry._1(dispatch, /* Identity_Add */{
                                  _0: id
                                });
                    }));
      });
}

export {
  fetchIdentities ,
}
/* Store Not a pure module */
