// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Store from "./Store.bs.js";
import * as Belenios from "../helpers/Belenios.bs.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";

function make(name, description, choices, ownerPublicKey) {
  var match = Belenios.Trustees.create(undefined);
  var trustees = match[1];
  Store.Trustee.add({
        pubkey: Belenios.Trustees.pubkey(trustees),
        privkey: match[0]
      });
  var params = Belenios.Election._create(name, description, choices, trustees);
  return {
          params: params,
          trustees: trustees,
          ownerPublicKey: ownerPublicKey
        };
}

function make$1(t, owner) {
  JSON.stringify(t);
  Belt_Option.getExn(owner.hexSecretKey);
}

var Signed = {
  make: make$1
};

export {
  make ,
  Signed ,
}
/* Store Not a pure module */
