// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Sjcl from "../helpers/Sjcl.bs.js";
import * as Curry from "rescript/lib/es6/curry.js";

function make(param) {
  var match = Sjcl.Ecdsa.$$new(undefined);
  return {
          hexPublicKey: Curry._1(Sjcl.Ecdsa.PublicKey.toHex, match[0]),
          hexSecretKey: Curry._1(Sjcl.Ecdsa.SecretKey.toHex, match[1]),
          email: undefined,
          phoneNumber: undefined
        };
}

export {
  make ,
}
/* Sjcl Not a pure module */
