// Generated by ReScript, PLEASE EDIT WITH CARE


function to_json(r) {
  return {
          election_id: r.electionId,
          choice_id: r.choiceId,
          token: r.token
        };
}

var initial = {
  electionId: 0,
  choiceId: 0,
  token: ""
};

export {
  initial ,
  to_json ,
}
/* No side effect */
