// Generated by ReScript, PLEASE EDIT WITH CARE


var Election = {};

var Ballot = {};

var User = {};

var initial_transactions = [];

var initial_cache = {
  elections: undefined,
  ballots: undefined
};

var initial_identities = [];

var initial_trustees = [];

var initial = {
  transactions: initial_transactions,
  cache: initial_cache,
  identities: initial_identities,
  trustees: initial_trustees
};

function reducer(state, action) {
  return [
          state,
          []
        ];
}

export {
  Election ,
  Ballot ,
  User ,
  initial ,
  reducer ,
}
/* No side effect */
