// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as AsyncStorage from "@react-native-async-storage/async-storage";

var keyName = "trusteesKeys";

function get(param) {
  return AsyncStorage.default.getItem(keyName).then(function (prim) {
                if (prim === null) {
                  return ;
                } else {
                  return Caml_option.some(prim);
                }
              }).then(function (os) {
              if (os !== undefined) {
                return JSON.parse(os);
              } else {
                return [];
              }
            });
}

function set(a) {
  return AsyncStorage.default.setItem(keyName, JSON.stringify(a));
}

function add(o) {
  get(undefined).then(function (a) {
        var a$1 = Belt_Array.concat(a, [o]);
        return AsyncStorage.default.setItem(keyName, JSON.stringify(a$1));
      });
}

function clean(param) {
  AsyncStorage.default.removeItem(keyName);
}

var Trustee = {
  keyName: keyName,
  get: get,
  set: set,
  add: add,
  clean: clean
};

var keyName$1 = "tokens";

function get$1(param) {
  return AsyncStorage.default.getItem(keyName$1).then(function (prim) {
                if (prim === null) {
                  return ;
                } else {
                  return Caml_option.some(prim);
                }
              }).then(function (os) {
              if (os !== undefined) {
                return JSON.parse(os);
              } else {
                return [];
              }
            });
}

function set$1(a) {
  return AsyncStorage.default.setItem(keyName$1, JSON.stringify(a));
}

function add$1(o) {
  get$1(undefined).then(function (a) {
        var a$1 = Belt_Array.concat(a, [o]);
        return AsyncStorage.default.setItem(keyName$1, JSON.stringify(a$1));
      });
}

function clean$1(param) {
  AsyncStorage.default.removeItem(keyName$1);
}

var Token = {
  keyName: keyName$1,
  get: get$1,
  set: set$1,
  add: add$1,
  clean: clean$1
};

export {
  Trustee ,
  Token ,
}
/* @react-native-async-storage/async-storage Not a pure module */
