// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belenios_jslib2 from "./belenios_jslib2";

function create(prim0, prim1) {
  return Belenios_jslib2.belenios.makeCredentials(prim0, prim1);
}

var Credentials = {
  create: create
};

var Privkey = {};

function create$1(prim) {
  return Belenios_jslib2.belenios.genTrustee();
}

var pubkey = (function(e) {
      var pubkey = JSON.parse(e)[0][1]["public_key"];
      console.log(pubkey);
      return pubkey;
    });

var Trustees = {
  Privkey: Privkey,
  create: create$1,
  pubkey: pubkey
};

var Ballot = {};

var PartialDecryption = {};

function create$2(prim0, prim1, prim2, prim3) {
  return Belenios_jslib2.belenios.makeElection(prim0, prim1, prim2, prim3);
}

function vote(prim0, prim1, prim2, prim3) {
  return Belenios_jslib2.belenios.encryptBallot(prim0, prim1, prim2, prim3);
}

function decrypt(prim0, prim1, prim2, prim3, prim4) {
  return Belenios_jslib2.belenios.decrypt(prim0, prim1, prim2, prim3, prim4);
}

function result(prim0, prim1, prim2, prim3, prim4, prim5) {
  return Belenios_jslib2.belenios.result(prim0, prim1, prim2, prim3, prim4, prim5);
}

var uuid = (function(e) {
      console.log(1);
      console.log(e);
      var uuid = JSON.parse(e)["uuid"];
      console.log(2)
      return uuid;
    });

var Election = {
  create: create$2,
  vote: vote,
  decrypt: decrypt,
  result: result,
  uuid: uuid
};

export {
  Credentials ,
  Trustees ,
  Ballot ,
  PartialDecryption ,
  Election ,
}
/* ./belenios_jslib2 Not a pure module */
