// Generated by ReScript, PLEASE EDIT WITH CARE


var base_url = "https://api.scrutin.app";

var api_prefix = "/v0";

var api_url = base_url + api_prefix;

export {
  base_url ,
  api_prefix ,
  api_url ,
}
/* No side effect */
