// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as Trustee from "./model/Trustee.bs.js";
import * as Election from "./model/Election.bs.js";
import * as Identity from "./model/Identity.bs.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Transaction from "./model/Transaction.bs.js";

function create(name, desc, choices, state, dispatch) {
  var identity = Belt_Array.get(state.ids, 0);
  var identity$1;
  if (identity !== undefined) {
    identity$1 = identity;
  } else {
    var identity$2 = Identity.make(undefined);
    Curry._1(dispatch, {
          TAG: /* Identity_Add */1,
          _0: identity$2
        });
    identity$1 = identity$2;
  }
  var trustee = Trustee.make(undefined);
  var election = Election.make(name, desc, choices, identity$1.hexPublicKey, trustee);
  var transaction = Transaction.SignedElection.make(election, identity$1);
  Curry._1(dispatch, {
        TAG: /* Transaction_Add */2,
        _0: transaction
      });
  Curry._1(dispatch, {
        TAG: /* Trustee_Add */3,
        _0: trustee
      });
  Curry._1(dispatch, {
        TAG: /* Navigate */0,
        _0: {
          TAG: /* Election_Show */0,
          _0: transaction.eventHash
        }
      });
}

var Election$1 = {
  create: create
};

export {
  Election$1 as Election,
}
/* Trustee Not a pure module */
