// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as ReactNativePaper from "react-native-paper";

function Navigation(Props) {
  var match = React.useState(function () {
        return 0;
      });
  var setIndex = match[1];
  return React.createElement(ReactNativePaper.BottomNavigation, {
              onIndexChange: (function (i) {
                  Curry._1(setIndex, (function (param) {
                          return i;
                        }));
                }),
              renderScene: (function (o) {
                  return React.createElement(ReactNativePaper.Text, {
                              children: o.route.title
                            });
                }),
              navigationState: {
                index: match[0],
                routes: [
                  {
                    key: "elections",
                    title: "Elections",
                    icon: "vote",
                    accessibilityLabel: undefined,
                    badge: undefined,
                    color: undefined,
                    testID: undefined
                  },
                  {
                    key: "identities",
                    title: "Identities",
                    icon: "account",
                    accessibilityLabel: undefined,
                    badge: undefined,
                    color: undefined,
                    testID: undefined
                  },
                  {
                    key: "transactions",
                    title: "Transactions",
                    icon: "thing",
                    accessibilityLabel: undefined,
                    badge: undefined,
                    color: undefined,
                    testID: undefined
                  }
                ]
              }
            });
}

var make = Navigation;

export {
  make ,
}
/* react Not a pure module */
