// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Sjcl = require("./Sjcl.bs.js");

function make(param) {
  var match = Sjcl.Ecdsa.$$new(undefined);
  return {
          publicKey: match[0],
          secretKey: match[1]
        };
}

exports.make = make;
/* Sjcl Not a pure module */
